import = ["/home/lkarasinski/.config/alacritty/catppuccin-mocha.toml"]

[font]
size = 12

[font.normal]
family = "FiraCode Nerd Font Mono"

[shell]
program = "/usr/bin/zsh"

[window]
decorations = "full"
opacity = 1

[window.dimensions]
columns = 180
lines = 55

[keyboard]
bindings = [
	{ key = "F11", action = "ToggleFullscreen" },
    { key = "Tab", mods = "Control", chars = "\u001b[27;5;9~" },
    { key = "Tab", mods = "Control|Shift", chars = "\u001b[27;6;9~" },
]
